version: "3"
services:
  web:
    image: nginx:1.18-alpine
    container_name: lv2_web
    ports:
      - 8080:80
    environment: 
      - TZ=${TZ}
    volumes:
      - ./laravel-app:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - app
  app:
    build:
      context: ./docker/php
      args: 
        - TZ=${TZ}
    container_name: lv2_app
    working_dir: /work
    environment: 
      - TZ=${TZ}
    volumes:
      - ./laravel-app:/work
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  db:
    image: mysql:5.7
    container_name: lv2_db
    ports: 
      - 13306:3306
    environment: 
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-store:/var/lib/mysql
volumes:
  db-store:
